# Generated by Django 2.0.4 on 2020-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('history', models.CharField(max_length=32)),
            ],
        ),
    ]
