# Generated by Django 2.0.4 on 2020-03-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
    ]
