# Generated by Django 2.0.4 on 2020-03-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0002_auto_20200329_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
